apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-chart.fullname" . }}
  namespace: {{ .Values.environment }}
spec:
  selector:
    app: {{ include "helm-chart.fullname" . }}
  ports:
    - port: 80
      targetPort: {{ .Values.application.port }}
  type: {{ .Values.configuration.type}}