auth-server:
  url: ${keycloak-client.server-url}
#  admin-secret: '{cipher}c56a188e7714b3f03bec9f20b1ad15497b54e7080cfcaf3f757c072db4458ee870e3982869bec08ee6659541192f7ffb3aa3e9b844a9d1674ab1e8c71a7a22e0'
  admin-secret: 530e9165-756c-4f2c-a9ac-5ff1c0cfd948
  cli-token-uri: auth/realms/master/protocol/openid-connect/token
  users-uri: auth/admin/realms/${keycloak-client.realm}/users
  email-actions-uri: auth/admin/realms/${keycloak-client.realm}/users/{id}/execute-actions-email
keycloak-client:
  server-url: auth-dev.agenadev.com
  realm: diar
profiles:
  url: http://localhost:8989
  path: api/v1/profiles
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
        loggerLevel: full
springdoc.api-docs.path: /api/v1/keycloak-adapter/api-doc
logging:
  level:
    com.agenatech: DEBUG
